#!/usr/bin/env python3
"""Transcribe the recoverable July Ozonetel recordings matched to Zoho calls.

The inventory JSON files are generated by the read-only CDR/Zoho scan. Output
is incremental in out/transcripts, so reruns skip every completed call.
"""
import argparse
import json
import time
from pathlib import Path
from urllib.parse import urlparse

import requests

from batch_transcribe import OUT, TDIR, run_sarvam_batch, save_results

BASE = Path(__file__).resolve().parent.parent
OZONE_CDR = BASE / "out/ozonetel_cdr_2026-07-21_to_31.json"
ZOHO_CALLS = BASE / "out/zoho_july21_31_gt30.json"
EXPORT_MATCHES = BASE / "out/ozonetel_july01_15_matches.json"


def duration_seconds(row):
    try:
        return int(row.get("Call_Duration_in_seconds") or 0)
    except (TypeError, ValueError):
        return 0


def candidates(source):
    done = {p.name.removesuffix(".mp3.json") for p in TDIR.glob("*.json")}
    if source == "export-july1-15":
        exported = json.loads(EXPORT_MATCHES.read_text())
        return [
            (item["zoho"], item["audio_url"])
            for item in exported
            if str(item["zoho"].get("id") or "") not in done
            and item.get("audio_url")
        ]

    ozone = json.loads(OZONE_CDR.read_text())
    zoho = json.loads(ZOHO_CALLS.read_text())
    audio_by_call_id = {
        str(row.get("CallID")): row["CallAudio"]
        for row in ozone if row.get("CallID") and row.get("CallAudio")
    }
    matched = []
    for row in zoho:
        crm_id = str(row.get("id") or "")
        recording = row.get("Voice_Recording__s") or ""
        provider_id = Path(urlparse(recording).path).name
        audio_url = audio_by_call_id.get(provider_id)
        if crm_id and crm_id not in done and audio_url:
            matched.append((row, audio_url))
    return matched


def download(url, destination, retries=4):
    partial = destination.with_suffix(".mp3.part")
    for attempt in range(retries):
        try:
            with requests.get(url, stream=True, timeout=180,
                              allow_redirects=True) as response:
                response.raise_for_status()
                with partial.open("wb") as handle:
                    for chunk in response.iter_content(1024 * 128):
                        if chunk:
                            handle.write(chunk)
            if partial.stat().st_size >= 1000:
                partial.replace(destination)
                return True
        except (OSError, requests.RequestException):
            pass
        partial.unlink(missing_ok=True)
        time.sleep(5 * (attempt + 1))
    return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch-size", type=int, default=20)
    parser.add_argument("--source", choices=("api-july21-31", "export-july1-15", "export-file"),
                        default="api-july21-31")
    parser.add_argument("--matches-file", default=None,
                        help="required when --source export-file; path to a matches "
                             "JSON built by build_ozonetel_csv_matches.py")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    batch_size = min(max(args.batch_size, 1), 20)
    if args.source == "export-file":
        if not args.matches_file:
            raise SystemExit("--source export-file requires --matches-file")
        global EXPORT_MATCHES
        EXPORT_MATCHES = Path(args.matches_file)
        pending = candidates("export-july1-15")  # same loader path, generic now
    else:
        pending = candidates(args.source)
    seconds = sum(duration_seconds(row) for row, _ in pending)
    print(f"Ozonetel source: {args.source}")
    print(f"Ozonetel recordings ready: {len(pending)}")
    print(f"Audio: {seconds / 60:.1f} min ({seconds / 3600:.1f} h)")
    print(f"Estimated Sarvam cost at INR 45/hour: INR {seconds / 3600 * 45:.2f}")
    if args.dry_run or not pending:
        return

    total_saved = 0
    batches = [pending[i:i + batch_size] for i in range(0, len(pending), batch_size)]
    for number, batch in enumerate(batches, 1):
        print(f"\n-- Ozonetel batch {number}/{len(batches)} --", flush=True)
        files, id_to_file = [], {}
        for row, url in batch:
            call_id = str(row["id"])
            destination = OUT / f"{call_id}.mp3"
            if download(url, destination):
                files.append(destination)
                id_to_file[call_id] = destination
                print(f"  downloaded {call_id} ({duration_seconds(row)}s)", flush=True)
            else:
                print(f"  unavailable {call_id}", flush=True)
        if not files:
            continue
        try:
            results = run_sarvam_batch(files)
            saved = save_results(results, id_to_file)
        except Exception as error:
            print(f"Batch failed: {type(error).__name__}: {error}", flush=True)
            raise
        total_saved += saved
        print(f"Saved {saved}; running total {total_saved}", flush=True)
        for path in files:
            path.unlink(missing_ok=True)
    print(f"\nCompleted Ozonetel transcription: {total_saved} new transcript(s)")


if __name__ == "__main__":
    main()
